services:
  web:
    container_name: tiles.briscycle.com
    build: .
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.briscycle-tiles.rule=Host(`tiles.briscycle.com`)"
      - "traefik.http.routers.briscycle-tiles.entrypoints=websecure"
      - "traefik.http.routers.briscycle-tiles.tls.certresolver=le"
      - "traefik.http.services.briscycle-tiles.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_default"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
